apiVersion: v1
kind: Service
metadata:
  labels:
    env: prod
  name: service-first
  namespace: myname-space
spec:
  selectors:
    matchLables:
      labels:
        env: prod
  type: nodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: prod
  name: deployment-first
  namespace: myname-space
spec:
  replicas: 2
  selectors:
    matchLabels:
      env: prod
      track: stable
  template:
    metadata:
      labels:
        env: prod
        track: stable
    spec:
      containers:
      - name: count-deploy
        image: deploying-images
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodeSeconds: 4
